"use client";
import {useState} from "react";
import {Button} from "@/components/ui/button";
import {Table,TableBody,TableCell,TableHead,TableHeader,TableRow} from "@/components/ui/table";
import {AlertTriangle,Link2} from "lucide-react";
import {ResponsiveContainer,BarChart,Bar,CartesianGrid,XAxis,YAxis,Tooltip,Legend,LineChart,Line} from "recharts";
import type {RunView} from "@/lib/buddy/client";
import {symbolName} from "@/lib/buddy/client";
const money=(n:number|null)=>n===null?"缺失":(n/1e8).toLocaleString("zh-CN",{maximumFractionDigits:2});
export default function DataOverview({view,onEvidence}:{view:RunView;onEvidence:(id:string)=>void}){
 const {run,comparison}=view,chart=comparison.rows.map(r=>({name:symbolName(r.symbol),收入:r.revenue===null?null:r.revenue/1e8,净利润:r.netProfit===null?null:r.netProfit/1e8,经营现金流:r.cashflow===null?null:r.cashflow/1e8})),series=run.evidence.filter(e=>e.series?.length&&e.quality==="valid");
 const [symbol,setSymbol]=useState("");const selected=series.find(e=>e.symbol===symbol)??series[0];
 return <div className="overview"><div className="metric-grid">{[{title:"共同财务报告期",value:comparison.period??"待核验",note:"年度累计 · CNY"}, {title:"已保存证据",value:String(run.evidence.length),note:"保留原始响应及哈希"}, {title:"数据状态",value:String(run.evidence.filter(e=>e.quality!=="valid").length),note:"缺失 / 过期 / 冲突"}].map(m=><div className="metric-card" key={m.title}><span>{m.title}</span><strong>{m.value}</strong><small>{m.note}</small></div>)}</div>
 {comparison.issues.length>0&&<div className="notice warning"><AlertTriangle size={16}/><div>{comparison.issues.map(i=><p key={i}>{i}</p>)}</div></div>}
 <section className="chart-panel"><div className="panel-heading"><div><h2>利润背后，现金流如何？</h2><p>{comparison.period??"共同报告期待核验"} · 合并净利润 · 单位：亿元 {run.mode==="demo"?"· 构造数据":""}</p></div></div>{comparison.period?<div className="chart-height"><ResponsiveContainer width="100%" height="100%"><BarChart data={chart} margin={{top:10,right:5,left:0,bottom:5}} accessibilityLayer><CartesianGrid strokeDasharray="3 5" vertical={false} stroke="#303c2d"/><XAxis dataKey="name" tick={{fill:"#a4b49a",fontSize:11}} axisLine={false} tickLine={false}/><YAxis tick={{fill:"#7f9076",fontSize:10}} axisLine={false} tickLine={false}/><Tooltip contentStyle={{background:"#20281d",border:"1px solid #405335",borderRadius:8,color:"#e3eedb"}}/><Legend wrapperStyle={{fontSize:11,paddingTop:12}}/><Bar dataKey="收入" fill="#536d43" radius={[3,3,0,0]}/><Bar dataKey="净利润" fill="#a6ef74" radius={[3,3,0,0]}/><Bar dataKey="经营现金流" fill="#81c6cf" radius={[3,3,0,0]}/></BarChart></ResponsiveContainer></div>:<p className="empty-inline">暂无有效共同报告期，已暂停横向比较。</p>}
 <Table><TableHeader><TableRow><TableHead>公司</TableHead><TableHead>营业收入 / 亿元</TableHead><TableHead>合并净利润 / 亿元</TableHead><TableHead>经营现金流 / 亿元</TableHead><TableHead>现金流 / 净利润</TableHead><TableHead>证据</TableHead></TableRow></TableHeader><TableBody>{comparison.rows.map(r=><TableRow key={r.symbol}><TableCell><strong>{symbolName(r.symbol)}</strong><small className="symbol-code">{r.symbol}</small></TableCell><TableCell>{money(r.revenue)}</TableCell><TableCell>{money(r.netProfit)}</TableCell><TableCell>{money(r.cashflow)}</TableCell><TableCell>{r.cashConversion===null?"不可比较":r.cashConversion.toFixed(2)+" ×"}</TableCell><TableCell>{r.evidenceIds.map(id=><button className="table-citation" key={id} aria-label={"查看证据 "+id} onClick={()=>onEvidence(id)}>{id}</button>)}</TableCell></TableRow>)}</TableBody></Table><p className="chart-footnote">图表由代码换算：原始 CNY 元 ÷ 100,000,000；比率 = 经营活动现金流净额 ÷ 合并净利润。缺失值留空，非正净利润不计算比率。</p></section>
 {selected&&<section className="chart-panel"><div className="panel-heading"><div><h2>历史价格，只作研究背景。</h2><p>前复权日线 · CNY 元/股 {run.mode==="demo"?"· 构造数据":""}</p></div><div className="mini-tabs">{series.map(e=><Button size="sm" variant={e.id===selected.id?"secondary":"ghost"} key={e.id} onClick={()=>setSymbol(e.symbol??"")}>{symbolName(e.symbol??"")}</Button>)}</div></div><div className="price-chart"><ResponsiveContainer width="100%" height="100%"><LineChart data={selected.series} accessibilityLayer><CartesianGrid strokeDasharray="3 5" vertical={false} stroke="#303c2d"/><XAxis dataKey="date" tickFormatter={d=>d.slice(5,10)} minTickGap={45} tick={{fill:"#7f9076",fontSize:10}} axisLine={false}/><YAxis domain={["auto","auto"]} tick={{fill:"#7f9076",fontSize:10}} axisLine={false}/><Tooltip contentStyle={{background:"#20281d",border:"1px solid #405335",color:"#e3eedb"}} labelFormatter={l=>String(l).slice(0,10)}/><Line dataKey="value" name="收盘价" stroke="#a6ef74" strokeWidth={2} dot={false} connectNulls={false}/></LineChart></ResponsiveContainer></div><Button variant="ghost" size="sm" onClick={()=>onEvidence(selected.id)}>核验日线原始数据 <Link2 size={13}/></Button></section>}
 </div>;
}
