"use client";
import {useState} from "react";import {Loader2,Trash2,Database} from "lucide-react";
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription,DialogFooter} from "@/components/ui/dialog";import {AlertDialog,AlertDialogContent,AlertDialogHeader,AlertDialogTitle,AlertDialogDescription,AlertDialogFooter,AlertDialogAction,AlertDialogCancel} from "@/components/ui/alert-dialog";import {Button} from "@/components/ui/button";import {Textarea} from "@/components/ui/textarea";import {Checkbox} from "@/components/ui/checkbox";import type {MemoryEntry} from "@/lib/buddy/types";
export function MemoryDialog({open,onClose,onSave,initial}:{open:boolean;onClose:()=>void;onSave:(text:string)=>Promise<void>;initial:string}){
 const [text,setText]=useState(initial),[confirmed,setConfirmed]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState("");
 async function save(){setBusy(true);setError("");try{await onSave(text);onClose()}catch(e){setError(e instanceof Error?e.message:"保存失败")}finally{setBusy(false)}}
 return <Dialog open={open} onOpenChange={v=>!v&&onClose()}><DialogContent><DialogHeader><div className="dialog-icon"><Database size={22}/></div><DialogTitle>确认写入长期记忆</DialogTitle><DialogDescription>下次研究会引用这些内容。请将待核验观点明确标注为推断；内容仅保存在当前个人空间。</DialogDescription></DialogHeader><label htmlFor="memory-text" className="form-label">记忆内容</label><Textarea id="memory-text" value={text} maxLength={2000} onChange={e=>setText(e.target.value)} rows={5}/><label className="confirm-label"><Checkbox checked={confirmed} onCheckedChange={v=>setConfirmed(v===true)}/> 我已检查内容，并确认写入长期状态</label>{error&&<p className="form-error" role="alert">{error}</p>}<DialogFooter><Button variant="outline" onClick={onClose}>取消</Button><Button disabled={!confirmed||!text.trim()||busy} onClick={save}>{busy&&<Loader2 className="animate-spin" size={14}/>} 确认保存</Button></DialogFooter></DialogContent></Dialog>;
}
export function MemoryPanel({memory,onAdd,onDelete}:{memory:MemoryEntry[];onAdd:()=>void;onDelete:(id:string)=>Promise<void>}){
 const [removing,setRemoving]=useState<MemoryEntry|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState("");
 return <section className="memory-panel"><div className="panel-heading"><div><span className="eyebrow">LONG-TERM CONTEXT</span><h1>研究会延续，记忆由你确认。</h1><p>最多 50 条。仅显式保存的内容进入新研究；删除不改变已经保存的研究快照。</p></div><Button onClick={onAdd}>新增记忆</Button></div>{memory.length?memory.map(m=><div className="memory-row" key={m.id}><Database size={17}/><div><p>{m.text}</p><small>{m.kind==="preference"?"研究偏好":"研究笔记"} · {new Date(m.createdAt).toLocaleDateString("zh-CN",{timeZone:"Asia/Shanghai"})}</small></div><Button variant="ghost" size="icon" aria-label="删除记忆" onClick={()=>{setRemoving(m);setError("")}}><Trash2 size={15}/></Button></div>):<div className="empty-inline">尚无长期记忆。保存偏好或已核验的研究笔记，让下一次研究从这里继续。</div>}<AlertDialog open={!!removing} onOpenChange={v=>!v&&!busy&&setRemoving(null)}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>删除这条记忆？</AlertDialogTitle><AlertDialogDescription>之后的新研究不会再引用它。历史研究中的记忆快照保留。</AlertDialogDescription></AlertDialogHeader>{error&&<p role="alert" className="form-error">{error}</p>}<AlertDialogFooter><AlertDialogCancel disabled={busy}>取消</AlertDialogCancel><AlertDialogAction disabled={busy} onClick={async e=>{e.preventDefault();if(!removing)return;setBusy(true);try{await onDelete(removing.id);setRemoving(null)}catch(err){setError(err instanceof Error?err.message:"删除失败")}finally{setBusy(false)}}}>确认删除</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog></section>;
}
