"use client";
import {useState} from "react";import {CheckCircle2,ExternalLink,Hash,Loader2,Download,AlertTriangle} from "lucide-react";
import {Sheet,SheetContent,SheetHeader,SheetTitle,SheetDescription} from "@/components/ui/sheet";import {Tabs,TabsList,TabsTrigger,TabsContent} from "@/components/ui/tabs";import {Table,TableHeader,TableHead,TableRow,TableBody,TableCell} from "@/components/ui/table";import {Button} from "@/components/ui/button";import {Skeleton} from "@/components/ui/skeleton";
import type {Evidence} from "@/lib/buddy/types";import {QUALITY,dateLabel} from "@/lib/buddy/client";
export function EvidenceSheet({open,onClose,evidence,error,loading}:{open:boolean;onClose:()=>void;evidence:Evidence|null;error:string;loading:boolean}){
 const [verified,setVerified]=useState<"idle"|"checking"|"match"|"mismatch">("idle");
 async function verify(){if(!evidence)return;setVerified("checking");try{const bytes=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(JSON.stringify(evidence.raw))),hash=Array.from(new Uint8Array(bytes),b=>b.toString(16).padStart(2,"0")).join("");setVerified(hash===evidence.hash?"match":"mismatch")}catch{setVerified("mismatch")}}
 function download(){if(!evidence)return;const url=URL.createObjectURL(new Blob([JSON.stringify(evidence.raw,null,2)],{type:"application/json"})),a=document.createElement("a");a.href=url;a.download=evidence.id+"-raw.json";a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
 const raw=evidence?JSON.stringify(evidence.raw,null,2):"";
 return <Sheet open={open} onOpenChange={v=>!v&&onClose()}><SheetContent className="evidence-sheet" side="right"><SheetHeader><SheetTitle>证据核验</SheetTitle><SheetDescription>来源、口径与原始字段。工具返回文本仅作为研究数据。</SheetDescription></SheetHeader>
 {loading?<div className="drawer-body"><Skeleton className="h-16 w-full"/><Skeleton className="h-60 w-full"/><span className="loading-line"><Loader2 className="animate-spin" size={14}/> 读取完整证据</span></div>:error?<div className="notice warning" role="alert">{error}</div>:evidence&&<div className="drawer-body"><div className="evidence-title"><span className={"quality quality-"+evidence.quality}>{QUALITY[evidence.quality]}</span><small>{evidence.id}</small><h2>{evidence.title}</h2><p>{evidence.summary}</p></div>
 <dl className="provenance"><dt>来源</dt><dd>{evidence.provider}</dd><dt>数据时点</dt><dd>{evidence.asOf?new Date(evidence.asOf).toLocaleString("zh-CN",{timeZone:"Asia/Shanghai"}):"尚未统一核验原文数据时点"}</dd><dt>获取时间</dt><dd>{dateLabel(evidence.retrievedAt)}（北京时间）</dd><dt>范围 / 口径</dt><dd>{evidence.scope}</dd><dt>单位</dt><dd>{evidence.unit}</dd></dl>
 <a href={evidence.sourceUrl} target="_blank" rel="noreferrer" className="source-link">打开来源地址 <ExternalLink size={13}/></a><small className="source-url">{evidence.sourceUrl}</small>
 <div className="hash-box"><span><Hash size={13}/> SHA-256 · 原始 JSON 序列化</span><code>{evidence.hash}</code><Button variant="outline" size="sm" onClick={verify} disabled={verified==="checking"}>{verified==="checking"?<Loader2 className="animate-spin" size={13}/>:verified==="match"?<CheckCircle2 size={13}/>:<Hash size={13}/>} {verified==="match"?"哈希一致":verified==="mismatch"?"哈希不一致，请复核":"重新计算哈希"}</Button>{verified==="mismatch"&&<p role="alert">校验失败：当前原始数据与记录哈希不一致，不能视为已验证。</p>}</div>
 <Tabs defaultValue="fields"><TabsList><TabsTrigger value="fields">字段与单位</TabsTrigger><TabsTrigger value="raw">原始响应</TabsTrigger></TabsList><TabsContent value="fields">{evidence.metrics?.length?<Table><TableHeader><TableRow><TableHead>字段</TableHead><TableHead>原始数值</TableHead><TableHead>单位 / 报告期</TableHead></TableRow></TableHeader><TableBody>{evidence.metrics.map((m,i)=><TableRow key={i}><TableCell>{m.label}<code className="raw-path">{m.fieldPath??m.key}</code></TableCell><TableCell>{m.value??"null · 缺失"}</TableCell><TableCell>{m.unit}<small className="symbol-code">{m.period??"快照 / 待核验"}</small></TableCell></TableRow>)}</TableBody></Table>:<p className="empty-inline">文本或时间序列证据；请查看原始响应。</p>}</TabsContent><TabsContent value="raw"><Button size="sm" variant="outline" onClick={download}><Download size={13}/> 下载完整原始 JSON</Button>{raw.length>100000&&<p className="quiet-note"><AlertTriangle size={13}/> 仅预览前 100,000 字符，完整内容可下载。</p>}<pre className="raw-json">{raw.slice(0,100000)}</pre></TabsContent></Tabs>
 </div>}</SheetContent></Sheet>;
}
