"use client";
import {useEffect,useRef} from "react";
type ModelTool={name:string;title:string;description:string;inputSchema:object;annotations:{readOnlyHint:boolean;untrustedContentHint:boolean};execute:(input:unknown)=>unknown|Promise<unknown>};
type ModelContext={registerTool:(tool:ModelTool,options?:{signal?:AbortSignal})=>void|Promise<void>};
export function useResearchTools(read:()=>unknown,stage:(goal:string,symbols:string[])=>void){
 const current=useRef({read,stage});useEffect(()=>{current.current={read,stage}},[read,stage]);
 useEffect(()=>{const context=(document as Document&{modelContext?:ModelContext}).modelContext;if(!context?.registerTool)return;const lifecycle=new AbortController();
 const tools:ModelTool[]=[{name:"read_research_state",title:"读取当前研究状态",description:"读取当前可见线程的进度、模式和用量，不返回密钥、会话或隐藏推理。",inputSchema:{type:"object",properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute(input){if(!input||typeof input!=="object"||Array.isArray(input)||Object.keys(input).length)throw new Error("参数必须是空对象");return current.current.read()}},{name:"stage_research_goal",title:"准备研究目标",description:"在可见的新研究表单中填写目标与A股代码。仅准备草稿，不生成计划、不调用金融接口；用户随后确认。",inputSchema:{type:"object",properties:{goal:{type:"string",minLength:1,maxLength:2000},symbols:{type:"array",minItems:1,maxItems:3,items:{type:"string",pattern:"^[0-9]{6}\\.(SH|SZ|BJ)$"}}},required:["goal","symbols"],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:true},async execute(input){if(!input||typeof input!=="object"||Array.isArray(input))throw new Error("研究参数无效");const obj=input as Record<string,unknown>;if(Object.keys(obj).some(k=>!["goal","symbols"].includes(k))||typeof obj.goal!=="string"||!obj.goal.trim()||obj.goal.length>2000||!Array.isArray(obj.symbols)||obj.symbols.length<1||obj.symbols.length>3||obj.symbols.some(s=>typeof s!=="string"||!/^\d{6}\.(SH|SZ|BJ)$/.test(s))||new Set(obj.symbols).size!==obj.symbols.length)throw new Error("目标或A股代码无效");current.current.stage(obj.goal,obj.symbols as string[]);await new Promise<void>(resolve=>requestAnimationFrame(()=>requestAnimationFrame(()=>resolve())));return {staged:true,goal:(document.getElementById("goal") as HTMLTextAreaElement|null)?.value??obj.goal,symbols:obj.symbols,requiresUserAction:true}}}];
 for(const tool of tools){try{void Promise.resolve(context.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{})}catch{/* Unsupported registries leave the visible workbench usable. */}}return()=>lifecycle.abort();
 },[]);
}
