"use client";
import {useCallback,useEffect,useRef,useState} from "react";
import {ArrowUpRight,Bot,CircleDot,FileSearch,GitBranch,Layers3,Plus,ShieldCheck,Sparkles,Workflow,Loader2,AlertCircle,RefreshCw} from "lucide-react";
import {Button} from "@/components/ui/button";import {Textarea} from "@/components/ui/textarea";import {Input} from "@/components/ui/input";import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from "@/components/ui/select";import {Skeleton} from "@/components/ui/skeleton";import {Toaster} from "@/components/ui/sonner";import {toast} from "sonner";
import {Sidebar,SidebarContent,SidebarFooter,SidebarHeader,SidebarInset,SidebarMenu,SidebarMenuButton,SidebarMenuItem,SidebarProvider,SidebarTrigger} from "@/components/ui/sidebar";
import {api,ApiError,STATUS,type Bootstrap,type RunView} from "@/lib/buddy/client";import type {RunMode,Evidence} from "@/lib/buddy/types";import {HarnessRail} from "./harness-rail";import {Results} from "./results";import {EvidenceSheet} from "./evidence-sheet";import {LoginDialog,MemoryDialog,MemoryPanel} from "./dialogs";
import {useResearchTools} from "./webmcp";
const INITIAL="比较贵州茅台、五粮液和泸州老窖的盈利质量与估值，找出需要继续验证的关键问题。";
export default function Workbench(){
 const [mode,setMode]=useState<RunMode>("demo"),[bootstrap,setBootstrap]=useState<Bootstrap|null>(null),[view,setView]=useState<RunView|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState(""),[page,setPage]=useState<"research"|"memory">("research"),[goal,setGoal]=useState(INITIAL),[symbols,setSymbols]=useState("600519.SH, 000858.SZ, 000568.SZ"),[scenario,setScenario]=useState("normal"),[toolLimit,setToolLimit]=useState("24"),[busy,setBusy]=useState(false),[loginOpen,setLoginOpen]=useState(false),[memoryOpen,setMemoryOpen]=useState(false),[memoryInitial,setMemoryInitial]=useState(""),[parentId,setParentId]=useState<string|undefined>(),[drawer,setDrawer]=useState(false),[evidence,setEvidence]=useState<Evidence|null>(null),[evidenceError,setEvidenceError]=useState(""),[evidenceLoading,setEvidenceLoading]=useState(false);
 const active=useRef<string|null>(null),modeRef=useRef(mode),inflight=useRef(false),drawerSeq=useRef(0),alive=useRef(true);
 modeRef.current=mode;
 useEffect(()=>{alive.current=true;const timer=setTimeout(()=>{if(localStorage.getItem("xb-mode")==="live")setMode("live")},0);return()=>{clearTimeout(timer);alive.current=false}},[]);
 const accept=useCallback((data:RunView,currentMode:RunMode)=>{if(!alive.current||modeRef.current!==currentMode||active.current!==data.run.id)return;setView(previous=>!previous||data.run.version>=previous.run.version?data:previous);setBootstrap(b=>b&&!((b.runs.find(r=>r.id===data.run.id)?.version??-1)>data.run.version)?{...b,runs:[{id:data.run.id,title:data.run.title,goal:data.run.goal,mode:data.run.mode,status:data.run.status,createdAt:data.run.createdAt,updatedAt:data.run.updatedAt,metrics:data.run.metrics,version:data.run.version,symbols:data.symbols,planning:data.planning},...b.runs.filter(r=>r.id!==data.run.id)].slice(0,30)}:b)},[]);
 const select=useCallback(async(id:string,currentMode:RunMode=mode,showResearch=true)=>{active.current=id;if(showResearch)setPage("research");setView(null);setError("");localStorage.setItem("xb-active-"+currentMode,id);try{accept(await api<RunView>("runs/"+id,currentMode),currentMode)}catch(e){if(active.current===id&&modeRef.current===currentMode)setError(e instanceof Error?e.message:"研究读取失败")}},[mode,accept]);
 const load=useCallback(async(currentMode:RunMode)=>{setLoading(true);setError("");try{const b=await api<Bootstrap>("bootstrap",currentMode);if(!alive.current||modeRef.current!==currentMode)return;setBootstrap(b);const saved=localStorage.getItem("xb-active-"+currentMode),id=b.runs.find(r=>r.id===saved)?.id;if(id)await select(id,currentMode,false);else{active.current=null;setView(null)}}catch(e){if(modeRef.current===currentMode){setError(e instanceof Error?e.message:"服务连接失败");if(e instanceof ApiError&&["AUTH_REQUIRED","MODE_FORBIDDEN","UNAUTHORIZED"].includes(e.code)){localStorage.setItem("xb-mode","demo");setMode("demo");setLoginOpen(false)}}}finally{if(modeRef.current===currentMode)setLoading(false)}},[select]);
 useEffect(()=>{const timer=setTimeout(()=>{active.current=null;setView(null);setBootstrap(null);void load(mode)},0);return()=>clearTimeout(timer)},[mode,load]);
 useEffect(()=>{if(!view||page!=="research")return;const id=view.run.id,currentMode=mode;
 const should=view.planning||view.run.status==="running";
 if(!should)return;
 let cancelled=false;const timer=setTimeout(async()=>{if(cancelled||inflight.current||active.current!==id)return;inflight.current=true;try{
 const data=view.executing?await api<RunView>("runs/"+id,currentMode):await api<RunView>("runs/"+id+"/advance",currentMode,{version:view.run.version});
 accept(data,currentMode);
 }catch(e){if(e instanceof ApiError&&["BUSY","VERSION_CONFLICT"].includes(e.code)){try{accept(await api<RunView>("runs/"+id,currentMode),currentMode)}catch{}}else if(active.current===id&&modeRef.current===currentMode){setError(e instanceof Error?e.message:"执行请求失败，请刷新检查点");try{accept(await api<RunView>("runs/"+id,currentMode),currentMode)}catch{}}}finally{inflight.current=false}},view.executing?1500:mode==="demo"?450:900);
 return()=>{cancelled=true;clearTimeout(timer)};
 },[view,mode,page,accept]);
 // A completed request may leave unchanged state after a lock response. Poll while another request owns the lease.
 useEffect(()=>{const timer=setInterval(()=>{if(view&&(view.planning||view.run.status==="running")&&!inflight.current&&active.current===view.run.id)void api<RunView>("runs/"+view.run.id,mode).then(d=>accept(d,mode)).catch(()=>{})},4000);return()=>clearInterval(timer)},[view,mode,accept]);
 useResearchTools(()=>({mode,thread:view?{id:view.run.id,status:view.run.status,planning:view.planning,completedSteps:view.run.checkpoint.completedTaskIds.length,totalSteps:view.run.plan.length,evidenceCount:view.run.evidence.length,metrics:view.run.metrics}:null}), (target,codes)=>{newResearch();setGoal(target);setSymbols(codes.join(", "))});
 function newResearch(){active.current=null;setView(null);setPage("research");setParentId(undefined);setError("");localStorage.removeItem("xb-active-"+mode)}
 async function create(){setBusy(true);setError("");try{const codes=symbols.split(/[,，\s]+/).filter(Boolean).map(s=>s.toUpperCase()),id=crypto.randomUUID();const data=await api<RunView>("runs",mode,{goal,symbols:codes,scenario,requestId:id,limits:{maxToolCalls:Number(toolLimit)},...(parentId?{parentId}: {})});active.current=data.run.id;localStorage.setItem("xb-active-"+mode,data.run.id);accept(data,mode)}catch(e){setError(e instanceof Error?e.message:"创建失败")}finally{setBusy(false)}}
 async function control(action:string,extra:object={}){if(!view)return;const id=view.run.id;setBusy(true);setError("");try{let data:RunView;try{data=await api<RunView>("runs/"+id+"/"+action,mode,{version:view.run.version,...extra})}catch(e){if(!(e instanceof ApiError)||e.code!=="VERSION_CONFLICT")throw e;const latest=await api<RunView>("runs/"+id,mode);accept(latest,mode);data=await api<RunView>("runs/"+id+"/"+action,mode,{version:latest.run.version,...extra})}accept(data,mode)}catch(e){setError(e instanceof Error?e.message:"状态更新失败")}finally{setBusy(false)}}
 async function openEvidence(id:string){if(!view)return;const seq=++drawerSeq.current;setDrawer(true);setEvidence(null);setEvidenceError("");setEvidenceLoading(true);try{const data=await api<Evidence>("runs/"+view.run.id+"/evidence/"+id,mode);if(seq===drawerSeq.current)setEvidence(data)}catch(e){if(seq===drawerSeq.current)setEvidenceError(e instanceof Error?e.message:"证据读取失败")}finally{if(seq===drawerSeq.current)setEvidenceLoading(false)}}
 async function exportResult(format:"markdown"|"json"){if(!view)return;try{const r=await fetch("/api/buddy/runs/"+view.run.id+"/export?mode="+mode+"&format="+format,{credentials:"same-origin",cache:"no-store"});if(!r.ok){const data=await r.json() as {error?:{message?:string}};throw new Error(data.error?.message??"导出失败")}const url=URL.createObjectURL(await r.blob()),a=document.createElement("a");a.href=url;a.download="XBuddy-"+view.run.id.slice(0,8)+(format==="json"?".json":".md");a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);toast.success("研究成果已导出，包含证据与核验信息")}catch(e){toast.error(e instanceof Error?e.message:"导出失败")}}
 async function login(code:string){await api("session","demo",{accessCode:code});setMode("live");localStorage.setItem("xb-mode","live");active.current=null;setView(null);setPage("research");toast.success("已进入真实研究空间")}
 async function switchMode(next:string){if(next==="live"){if(bootstrap?.session.mode==="live"){setMode("live");localStorage.setItem("xb-mode","live")}else setLoginOpen(true)}else{setMode("demo");localStorage.setItem("xb-mode","demo")}}
 function remember(){setMemoryInitial(view?.run.report?"研究笔记（推断）："+view.run.report.summary.slice(0,1300):"");setMemoryOpen(true)}
 async function saveMemory(text:string){const data=await api<{memory:Bootstrap["memory"]}>("memory",mode,{text,kind:view?"research":"preference",confirmed:true});setBootstrap(b=>b?{...b,memory:data.memory}:b);toast.success("长期记忆已保存")}
 function continuation(){if(!view)return;const id=view.run.id;setParentId(id);setGoal("基于上一份研究，继续核验现金回收变化的原因和相关公告。");setSymbols(view.symbols.join(", "));active.current=null;setView(null);setPage("research");localStorage.removeItem("xb-active-"+mode)}
 return <SidebarProvider style={{"--sidebar-width":"244px"} as React.CSSProperties}><Sidebar className="buddy-sidebar"><SidebarHeader className="brand"><div className="brand-mark"><GitBranch size={22}/></div><div><strong>X BUDDY</strong><span>投资研究工作台</span></div></SidebarHeader><SidebarContent><div className="nav-section">WORKSPACE / 工作区</div><SidebarMenu><SidebarMenuItem><SidebarMenuButton isActive={page==="research"} size="lg" onClick={()=>setPage("research")}><Workflow/><span>研究工作台</span><span className="nav-count">{String(bootstrap?.runs.length??0).padStart(2,"0")}</span></SidebarMenuButton></SidebarMenuItem><SidebarMenuItem><SidebarMenuButton isActive={page==="memory"} size="lg" onClick={()=>setPage("memory")}><Layers3/><span>长期记忆</span><span className="nav-count">{bootstrap?.memory.length??0}</span></SidebarMenuButton></SidebarMenuItem></SidebarMenu>
 <Button className="new-thread" variant="outline" onClick={newResearch}><Plus size={15}/> 新建研究</Button><div className="thread-heading"><span>研究线程</span><span>{mode==="demo"?"演示":"个人"}</span></div>
 {loading?<Skeleton className="h-24 w-full"/>:bootstrap?.runs.length?<div className="thread-list">{bootstrap.runs.map(r=><button key={r.id} onClick={()=>void select(r.id)} className={view?.run.id===r.id?"active":""}><span className={"thread-dot status-"+r.status}/><strong>{r.title}</strong><small>{r.planning?"规划中":STATUS[r.status]}</small></button>)}</div>:<div className="thread-empty">从一个研究问题开始。<br/>计划、证据与进度将在这里保留。</div>}<div className="sidebar-note"><CircleDot size={14}/><span>每一步，都有据可查。</span></div></SidebarContent><SidebarFooter className="profile"><div className="profile-avatar">研</div><div><strong>个人研究空间</strong><small>{mode==="demo"?"公开演示 · 构造数据":"访问码已验证 · 真实接口"}</small></div></SidebarFooter></Sidebar>
 <SidebarInset><header className="topbar"><div className="breadcrumb"><SidebarTrigger aria-label="展开侧栏"/><span>工作区</span><span>/</span><b>{page==="memory"?"长期记忆":view?"研究线程":"新研究"}</b></div><Select value={mode} onValueChange={v=>void switchMode(v)}><SelectTrigger className="mode-badge" aria-label="研究模式"><span className="status-dot"/><SelectValue/></SelectTrigger><SelectContent><SelectItem value="demo">演示 · 构造数据</SelectItem><SelectItem value="live">真实研究 · 访问码</SelectItem></SelectContent></Select></header>
 <div className="workspace"><main className="main-column">{error&&<div className="notice warning" role="alert"><AlertCircle size={17}/><div><strong>{error}</strong><Button variant="ghost" size="sm" onClick={()=>view?void api<RunView>("runs/"+view.run.id,mode).then(d=>{accept(d,mode);setError("")}).catch(e=>setError(e.message)):void load(mode)}><RefreshCw size={13}/> 重新读取状态</Button></div></div>}
 {loading?<div className="loading-workspace"><Skeleton className="h-12 w-3/4"/><Skeleton className="h-56 w-full"/><span><Loader2 size={16} className="animate-spin"/> 恢复个人研究空间</span></div>:page==="memory"?<MemoryPanel memory={bootstrap?.memory??[]} onAdd={()=>{setMemoryInitial("");setMemoryOpen(true)}} onDelete={async id=>{const data=await api<{memory:Bootstrap["memory"]}>("memory/"+id,mode,{},"DELETE");setBootstrap(b=>b?{...b,memory:data.memory}:b)}}/>:view?<Results view={view} tools={bootstrap?.tools??[]} busy={busy} onControl={(action,extra)=>void control(action,extra)} onEvidence={id=>void openEvidence(id)} onExport={f=>void exportResult(f)} onRemember={remember} onContinue={continuation}/>:<>
 <div className="page-heading"><div><span className="eyebrow">RESEARCH, WITH A TRACE.</span><h1>把问题，变成有证据的研究。</h1><p>你定义方向，Buddy 规划步骤、核验数据，并保留完整研究过程。</p></div><div className="hero-icon"><FileSearch size={32}/></div></div>
 <form onSubmit={e=>{e.preventDefault();void create()}} className="goal-card"><div className="section-top"><span><Sparkles size={17}/> 新的研究目标</span><span className="tiny-label">A 股 · 公司与同业比较</span></div><label htmlFor="goal" className="sr-only">研究目标</label><Textarea id="goal" className="goal-input" value={goal} onChange={e=>setGoal(e.target.value)} maxLength={2000} required/><div className="goal-options"><label className="form-label" htmlFor="symbols">研究代码 · 最多 3 家</label><Input id="symbols" value={symbols} onChange={e=>setSymbols(e.target.value)} placeholder="600519.SH, 000858.SZ" required/>{parentId&&<span className="parent-hint">已绑定上一研究作为背景；新任务需要重新审批。</span>}<details className="advanced"><summary>研究边界与演示场景</summary><div><label htmlFor="tool-budget" className="form-label">工具调用预算（0–24，含重试）</label><Input id="tool-budget" type="number" min={0} max={24} step={1} value={toolLimit} onChange={e=>setToolLimit(e.target.value)}/>{mode==="demo"&&<><label className="form-label">演示场景</label><Select value={scenario} onValueChange={setScenario}><SelectTrigger aria-label="演示场景"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="normal">完整数据 · 正常执行</SelectItem><SelectItem value="missing">现金流缺失 · 保留未知</SelectItem><SelectItem value="failure">接口失败 · 暂停后恢复</SelectItem></SelectContent></Select></>}<p>演示仅支持示例中的三家公司。真实研究支持准确 A 股代码。模型最多 4 次、预算 $0.50、运行最多 15 分钟。</p></div></details></div><div className="goal-footer"><span><ShieldCheck size={14}/> {mode==="demo"?"构造数据 · 不产生付费调用":"生成计划将调用模型；执行前确认工具"}</span><Button type="submit" disabled={busy||!bootstrap||!goal.trim()}>{busy?<Loader2 className="animate-spin" size={15}/>:null}生成研究计划 <ArrowUpRight size={16}/></Button></div></form>
 <div className="suggestion-label">从这些问题开始</div><div className="suggestions"><button onClick={()=>setGoal("比较三家公司经营现金流与合并净利润的关系，核验利润增长是否得到现金回收支撑。")}><span>01 / 盈利质量</span><strong>利润增长，是否有现金流支撑？</strong><p>核验财务口径与同业表现</p><ArrowUpRight size={18}/></button><button onClick={()=>setGoal("比较三家公司当前估值与盈利质量，区分财务事实、估值假设和需要核验的风险。")}><span>02 / 估值比较</span><strong>估值差异背后，有哪些假设？</strong><p>把事实、推断和未知分开</p><ArrowUpRight size={18}/></button></div>
 <section className="journey"><div className="section-top"><span><Workflow size={17}/> 研究如何推进</span><span className="tiny-label">可暂停 · 可恢复 · 可追溯</span></div><div className="journey-grid">{["明确研究目标","审批执行计划","获取并核验证据","交付可验证成果"].map((s,i)=><div key={s}><span className="step-number">0{i+1}</span><strong>{s}</strong><p>{["圈定公司与研究边界","检查工具、调用数与费用","保留原始响应和数据口径","逐条引用、导出与复用"][i]}</p></div>)}</div></section><div className="quiet-note"><Bot size={16}/><p>{mode==="demo"?"演示使用明确标注的构造数据。真实研究通过访问码开启。":"模型文字作为推断；财务数字由原始字段核验。"} 关闭页面后不持续调度，重新打开恢复保存的检查点。</p></div></>}</main><HarnessRail view={view} bootstrap={bootstrap}/></div></SidebarInset>
 <LoginDialog open={loginOpen} onClose={()=>setLoginOpen(false)} onLogin={login} available={bootstrap?.capabilities.liveAvailable??false}/>{memoryOpen&&<MemoryDialog open={memoryOpen} onClose={()=>setMemoryOpen(false)} onSave={saveMemory} initial={memoryInitial}/>}<EvidenceSheet key={evidence?.id??"loading"} open={drawer} onClose={()=>{setDrawer(false);drawerSeq.current++}} evidence={evidence} error={evidenceError} loading={evidenceLoading}/><Toaster richColors position="bottom-right"/></SidebarProvider>;
}
