import test from "node:test";import assert from "node:assert/strict";
import { parsePlanResponse, parseReviewResponse, estimateUsage, modelReservation } from "../lib/buddy/model.ts";
import { curatedTools } from "../lib/buddy/providers.ts";
const call=(name:string,args:unknown)=>({status:"completed",output:[{type:"function_call",name,arguments:JSON.stringify(args)}]});
const config={};
test("review high reasoning has 12000 output capacity and reservation follows payload",()=>{const payload=reviewPayload("盈利质量",[],{},"",{});assert.equal(payload.max_output_tokens,12000);assert.deepEqual(payload.reasoning,{effort:"high"});assert.equal(planningPayload("盈利质量",["600519.SH"],curatedTools(),[],new Date().toISOString(),{}).max_output_tokens,3000);assert.ok(modelReservation(payload,Number(payload.max_output_tokens),{})>0.0144)});
test("model plan is parsed from function calls, rejects unknown functions and unknown stock scope",()=>{const output=call("propose_research_plan",{title:"盈利质量",limitations:[],tasks:[{title:"收入",tool:"fuyao_income",arguments_json:'{"symbol":"600519.SH"}'},{title:"现金",tool:"fuyao_cashflow",arguments_json:'{"symbol":"600519.SH"}'},{title:"估值",tool:"fuyao_valuation",arguments_json:'{"symbol":"600519.SH"}'}]});const p=parsePlanResponse(output,curatedTools(),["600519.SH"]);assert.equal(p.tasks.length,3);const bad=structuredClone(output);bad.output[0].name="execute_shell";assert.throws(()=>parsePlanResponse(bad,curatedTools(),["600519.SH"]));assert.throws(()=>parsePlanResponse(output,curatedTools(),["000858.SZ"]))});
test("model plan cannot bypass schema, duplicate calls or omit comparison fundamentals",()=>{for(const tasks of [[{title:"x",tool:"fuyao_income",arguments_json:'{"symbol":"600519.SH","url":"https://evil.test"}'}],[{title:"x",tool:"fuyao_income",arguments_json:'{"symbol":"600519.SH"}'},{title:"y",tool:"fuyao_income",arguments_json:'{"symbol":"600519.SH"}'}]])assert.throws(()=>parsePlanResponse(call("propose_research_plan",{title:"t",limitations:[],tasks}),curatedTools(),["600519.SH"]))});
test("review cannot invent evidence IDs or manufacture facts",()=>{const raw={summary:"待进一步核验",claims:[{kind:"inference",text:"须核验现金流差异。",evidence_ids:["e1"]}],limitations:["供应商数据"],questions:["为何变化？"]};assert.equal(parseReviewResponse(call("write_evidence_review",raw),["e1"]).claims[0].kind,"inference");const bad=structuredClone(raw);bad.claims[0].evidence_ids=["invented"];assert.throws(()=>parseReviewResponse(call("write_evidence_review",bad),["e1"]));bad.claims[0].kind="fact";assert.throws(()=>parseReviewResponse(call("write_evidence_review",bad),["invented"]))});
test("usage includes cached input price and actual output, missing usage is rejected",()=>{const u=estimateUsage({input_tokens:1000,output_tokens:100,input_tokens_details:{cached_tokens:500}},config);assert.equal(u.inputTokens,1000);assert.equal(u.outputTokens,100);assert.ok(Math.abs(u.estimatedUsd-0.000273)<1e-12);assert.throws(()=>estimateUsage({},config));assert.ok(modelReservation({input:"中文目标"},3000,config)>0.0036)});

import { planningPayload, reviewPayload } from "../lib/buddy/model.ts";
test("thinking mode uses supported auto tool choice and still requires registered function parsing",()=>{const p=planningPayload("盈利质量",["600519.SH"],curatedTools(),[],new Date().toISOString(),{});assert.equal(p.tool_choice,"auto");const r=reviewPayload("盈利质量",[],{},"",{});assert.equal(r.tool_choice,"auto")});

test("planning leaves execution retry headroom and ticker search is a single exact confirmed code",()=>{const symbols=["600519.SH","000858.SZ","000568.SZ"];const tasks=symbols.flatMap(s=>["income","cashflow","valuation","balance","history","quote"].map(k=>({title:s+k,tool:"fuyao_"+k,arguments_json:JSON.stringify({symbol:s})}))).concat(symbols.map(s=>({title:s+"公司",tool:"ifind_company",arguments_json:JSON.stringify({query:s+" 公司信息"})})));assert.throws(()=>parsePlanResponse(call("propose_research_plan",{title:"t",limitations:[],tasks}),curatedTools(),symbols));const core=tasks.slice(0,3);const combined={title:"身份",tool:"fuyao_search",arguments_json:JSON.stringify({query:"600519.SH 贵州茅台"})};assert.throws(()=>parsePlanResponse(call("propose_research_plan",{title:"t",limitations:[],tasks:[combined,...core]}),curatedTools(),["600519.SH"]))});

const validPlan=()=>({title:"年度研究",limitations:[],tasks:["income","cashflow","valuation"].map(k=>({title:k,tool:"fuyao_"+k,arguments_json:JSON.stringify({symbol:"600519.SH"})}))});
const validReview=()=>({summary:"待核验",claims:[{kind:"inference",text:"核验差异。",evidence_ids:["e1"]}],limitations:[],questions:[]});
test("plan function arguments reject undeclared top-level properties",()=>{assert.throws(()=>parsePlanResponse(call("propose_research_plan",{...validPlan(),extra:"unexpected"}),curatedTools(),["600519.SH"]))});
test("plan function arguments reject undeclared task properties",()=>{const p=validPlan();Object.assign(p.tasks[0],{extra:"unexpected"});assert.throws(()=>parsePlanResponse(call("propose_research_plan",p),curatedTools(),["600519.SH"]))});
test("review function arguments reject undeclared top-level properties",()=>{assert.throws(()=>parseReviewResponse(call("write_evidence_review",{...validReview(),extra:"unexpected"}),["e1"]))});
test("review function arguments reject undeclared claim properties",()=>{const r=validReview();Object.assign(r.claims[0],{extra:"unexpected"});assert.throws(()=>parseReviewResponse(call("write_evidence_review",r),["e1"]))});

test("review parser and schema agree on ten bounded questions",()=>{const p=reviewPayload("研究",[],{},"",{});const schema=(p.tools as Array<{parameters:{properties:{questions:{maxItems:number};limitations:{maxItems:number};claims:{items:{properties:{evidence_ids:{maxItems:number}}}}}}}>)[0].parameters;assert.equal(schema.properties.questions.maxItems,10);assert.equal(schema.properties.limitations.maxItems,10);assert.equal(schema.properties.claims.items.properties.evidence_ids.maxItems,10)});
