import test from "node:test";
import assert from "node:assert/strict";
import { ProviderError, requestJson, parseRpc, createFuyaoUrl, curatedTools } from "../lib/buddy/providers.ts";
test("HTTP and business authentication failures are terminal and do not leak response secrets",async()=>{for(const response of [new Response("secret-key",{status:401}),Response.json({code:2003,message:"secret-key"})]){await assert.rejects(()=>requestJson("https://fuyao.aicubes.cn/api/test",{},{fetcher:async()=>response}),e=>e instanceof ProviderError&&!e.retryable&&!e.message.includes("secret-key"))}});
test("rate limit carries bounded retry-after, server faults retry, malformed JSON does not",async()=>{await assert.rejects(()=>requestJson("https://fuyao.aicubes.cn/api/test",{},{fetcher:async()=>new Response("",{status:429,headers:{"Retry-After":"9"}})}),e=>e instanceof ProviderError&&e.retryable&&e.retryAfterMs===9000);await assert.rejects(()=>requestJson("https://fuyao.aicubes.cn/api/test",{},{fetcher:async()=>new Response("",{status:503})}),e=>e instanceof ProviderError&&e.retryable);await assert.rejects(()=>requestJson("https://fuyao.aicubes.cn/api/test",{},{fetcher:async()=>new Response("garbled")}),e=>e instanceof ProviderError&&!e.retryable)});
test("response byte cap prevents oversize provider output",async()=>{await assert.rejects(()=>requestJson("https://fuyao.aicubes.cn/api/test",{},{fetcher:async()=>new Response("a".repeat(101)),maxBytes:100}),e=>e instanceof ProviderError&&e.code==="RESPONSE_TOO_LARGE")});
test("RPC supports JSON and SSE but rejects mismatched IDs and error envelopes",()=>{assert.deepEqual(parseRpc('{"jsonrpc":"2.0","id":1,"result":{"tools":[]}}',1),{tools:[]});assert.deepEqual(parseRpc('event: message\ndata: {"jsonrpc":"2.0","id":1,"result":{"content":[]}}\n\n',1),{content:[]});assert.throws(()=>parseRpc('{"jsonrpc":"2.0","id":2,"result":{}}',1));assert.throws(()=>parseRpc('{"jsonrpc":"2.0","id":1,"error":{"message":"upstream"}}',1))});
test("provider URL is allowlisted and validated, cannot supply arbitrary URLs or finance periods",()=>{assert.match(createFuyaoUrl("fuyao_income",{symbol:"600519.SH"}),/period=annual/);assert.throws(()=>createFuyaoUrl("fuyao_income",{symbol:"https://evil.test"}));assert.throws(()=>createFuyaoUrl("execute",{url:"https://evil.test"}));assert.ok(curatedTools().every(t=>t.permission==="read"&&t.requiresApproval))});

import {extractMcpText} from "../lib/buddy/providers.ts";
test("embedded MCP business errors are not mistaken for success text and successful answers remain readable",()=>{assert.equal(extractMcpText({content:[{type:"text",text:JSON.stringify({code:1,msg:"success",data:{answer:"公司资料"}})}]}),"公司资料");assert.throws(()=>extractMcpText({content:[{type:"text",text:JSON.stringify({code:2003,msg:"private-secret"})}]}),e=>e instanceof ProviderError&&!e.retryable&&!e.message.includes("private-secret"));assert.equal(extractMcpText({content:[{type:"text",text:"普通检索文本"}]}),"普通检索文本")});

test("Workers compatible manual redirects never forward provider credentials",async()=>{let calls=0;await assert.rejects(()=>requestJson("https://fuyao.aicubes.cn/api/test",{headers:{Authorization:"private-test"}},{fetcher:async(_url,init)=>{calls++;assert.equal(init?.redirect,"manual");return new Response("",{status:302,headers:{Location:"https://evil.test/steal"}})}}),e=>e instanceof ProviderError&&e.code==="REDIRECT_BLOCKED"&&!e.retryable);assert.equal(calls,1)});
